import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import { useQuery } from '@apollo/client';
import { gql } from '@apollo/client';
import { withApollo } from '../../hocs/withApollo';
import { useRouter } from 'next/router';
import Link from 'next/link';

const NodeDetail = () => {
  const { query } = useRouter();
  const { nodeId } = query;
  const { data, loading } = useQuery(
    gql`
      query nodeDetail($id: String!) {
        nodeDetail(id: $id) {
          id
          title
          description
        }
      }
    `,
    {
      variables: { id: nodeId },
    }
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>{loading ? 'Details' : data.nodeDetail.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{loading ? 'title loading...' : data.nodeDetail.title}</h1>

        <p className={styles.description}>{loading ? 'loading' : data.nodeDetail.description}</p>

        <Link href="/">
          <a>
            <h2 className={styles.back}>&larr; Back</h2>
          </a>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default NodeDetail;
