import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { useQuery } from '@apollo/client';
import { gql } from '@apollo/client';
import { withApollo } from '../hocs/withApollo';

const useLayoutQuery = () =>
  useQuery(gql`
    query layout {
      layout {
        id
        nodes {
          id
          templateId
          title
          href
        }
      }
    }
  `);

const ClubCardsTombstones = () => {
  return <div className={styles.tombstone} />;
};

const ClubCards = ({ id }) => {
  const { data, loading } = useQuery(
    gql`
      query nodeDetail($id: String!) {
        nodeDetail(id: $id) {
          id
          title
          description
        }
      }
    `,
    {
      ssr: false,
      variables: { id },
    }
  );

  return loading ? <ClubCardsTombstones /> : <p>{data.nodeDetail.description}</p>;
};

const CoursesTableTombstones = () => {
  return (
    <div>
      <div className={styles.tombstone} />
      <div className={styles.tombstone} style={{ width: '50%', marginTop: '2px' }} />
    </div>
  );
};

const CoursesTable = ({ id }) => {
  const { data, loading } = useQuery(
    gql`
      query nodeDetail($id: String!) {
        nodeDetail(id: $id) {
          id
          title
          description
        }
      }
    `,
    {
      ssr: false,
      variables: { id },
    }
  );
  return loading ? <CoursesTableTombstones /> : <p>{data.nodeDetail.description}</p>;
};

const TEMPLATE_ID_TO_COMPONENT = {
  'card-list/clubs': ClubCards,
  'table/courses': CoursesTable,
};

const Home = () => {
  const { data, loading } = useLayoutQuery();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js + Apollo!</a>
        </h1>

        <p className={styles.description}>Server Side Render</p>

        <div className={styles.grid}>
          {loading ? (
            <div>loading</div>
          ) : (
            data.layout.nodes.map((node) => {
              const Component = TEMPLATE_ID_TO_COMPONENT[node.templateId];
              return (
                <Link href={`/node/${node.href}`} key={node.id}>
                  <a className={styles.card}>
                    <div>
                      <h2>{node.title} &rarr;</h2>
                      <Component id={node.id} />
                    </div>
                  </a>
                </Link>
              );
            })
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
